### ISSUE TITLE
[3.3] Read Pressure Transducers

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/PDP-Monitoring-System#11]
[comment]: # (Reminder: Add to a milestone)
[comment]: # (Reminder: add labels)

# Description
[comment]: # (Describe what the feature or bug that need to be resolved)
[comment]: # (List if applicable: libraries, sensors, hardware, small parts of code you have to work on)

Back to basics. Wire one pressure transducer to the labjack and get a optimal reading. This includes having the correct gain offset to get a pressure that seems nominal.

# Acceptance Criteria
[comment]: # (Write specifically what is need for this issue to be completed)

- [x] Pressure transducer reads ambient values when no pressure is applied
- [x] Test with air compressor and make sure the readings match for a range of pressures
- [x] Read sensor in using the LJ differential mode in stream mode
- [x] Adjust LJ gain. 

# QA Notes
[comment]: # (how to test your ticket)

See [read_labjack.py](https://github.com/UVicRocketry/PDP-Monitoring-System/blob/corrected-channel-config/VC/instrumentation/read_labjack.py) for implementation details. In short, the wrong bits in the channel config byte were being set in the previous attempts at reading differential. This is now corrected and made more simple to use with modes that are OR'd together before passing to `streamConfig()`.

An additional issue was a hardware failure (multiplexer IC on the Mux80 let the magic smoke out) which made debugging the software much harder than it should've been. This has also been resolved now.

Gains and offsets were taken from the Kulite calibration sheets. A small unit conversion modification was made because they give values in psi/V and we want SI units. Since the sensors run at 10V nominal and we are now running at 5V (the boost converter used to generate 10V was very noisy), the values were multiplied by 10V/5V = 2.

Sensors were tested at ambient pressure and read about 18 psi (should read ~15), and using the cheapo regulator in the room appear to be accurate to within a couple psi. Noise from the sensor readings is about +-0.2psi while the valve cart controls system is powered off, and +-5psi while it is active likely due to excessive noise.

## Linked issues
[comment]: # (If there are any related or blocker issues)

**Comment by jjderooy** [comment]
@klemie what are dev notes?

**Comment by klemie** [comment]
@jjderooy Honestly these are pretty unnecessary. Its similar to comments on a PR, just document any weird things that happened when developing
