### ISSUE TITLE
Update Logger events

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/PDP-Monitoring-System#26]
[comment]: # (Reminder: Add to a milestone)
[comment]: # (Reminder: add labels)

# Description
[comment]: # (Describe what the feature or bug that need to be resolved)
[comment]: # (List if applicable: libraries, sensors, hardware, small parts of code you have to work on)

Currently we have a logger per file. However they do not log all of the things that they should! For the scope of this ticket audit the code and figure out if were logging enough event and where we should add some. Then do it 👍! Have two logs one for events and one for just data.

# Acceptance Criteria
[comment]: # (Write specifically what is need for this issue to be completed)

- [ ] Labjack logger report on sufficient results (upto reviewer). This should not log data just events
- [ ] Serail Interface logger reports on sufficient results.  
- [ ] All logs are compiled in one place

# QA Notes
[comment]: # (how to test your ticket)

## Linked issues
[comment]: # (If there are any related or blocker issues)

blocked by #25
