### ISSUE TITLE
Seperate Thermocouple Calcs to New File

### ISSUE THREAD

**Issue by jjderooy** [UVicRocketry/PDP-Monitoring-System#29]
[comment]: # (Reminder: Add to a milestone)
[comment]: # (Reminder: add labels)

# Description
[comment]: # (Describe what the feature or bug that need to be resolved)
[comment]: # (List if applicable: libraries, sensors, hardware, small parts of code you have to work on)
Right now, Aidan's thermocouple code is just dumped into `read_labjack.py`. I think it would make more sense to make a `thermocouple.py` that contains the function `get_ref_voltage()` and `V_to_K()`. Then we import this into `read_labjack.py` and use as needed.

# Acceptance Criteria
[comment]: # (Write specifically what is need for this issue to be completed)
- [x] Create new file called `thermocouple.py` that contains the `V_to_K()` function currently in `read_labjack.py`.
- [x] Remove current thermocouple code from `read_labjack.py` and import the functions in `thermocouple.py` to replace them.
- [x] Add some comments in `thermocouple.py` that describe where the function parameters came from, units etc.

# Dev Notes
[comment]: # (write down your thought process when developing this issue)

# QA Notes
[comment]: # (how to test your ticket)

## Linked issues
[comment]: # (If there are any related or blocker issues)

**Comment by jjderooy** [comment]
See comment on #35. This is pretty much ready to go, there is just a small (~7K) temp discrepancy right now that I haven't been able to resolve yet.
