### ISSUE TITLE
Update to docs

### ISSUE THREAD

**Issue by klemie** [UVicRocketry/PDP-Monitoring-System#33]
[comment]: # (Reminder: Add to a milestone)
[comment]: # (Reminder: add labels)

# Description
[comment]: # (Describe what the feature or bug that need to be resolved)
[comment]: # (List if applicable: libraries, sensors, hardware, small parts of code you have to work on)

Some stuff is not completely documents:
- Websocket api 
- new labjack implementation
- port over all docs from directed studies report

# Acceptance Criteria
[comment]: # (Write specifically what is need for this issue to be completed)

- [ ] passes the @nolanb10 check
- [ ] passes the Kris check 
- [ ] passes the @hToupin  check

# QA Notes
[comment]: # (how to test your ticket)

## Linked issues
[comment]: # (If there are any related or blocker issues)
